version: "3.5"
services:
  api1:
    image: magnus9999/rinha-de-backend-2023-q3-nebulonix
    hostname: api1
    # build: .
    depends_on:
      - db
    expose:
      - "80"
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 0.5GB

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 0.5GB

  db:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=rinha-de-backend-2023-q3
      - POSTGRES_PASSWORD=password123
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 1.5GB

